// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCm2edtdbvMku8A5edTbmGUtsyCC1TX7Js',
    appId: '1:1020559633116:web:de38d2b4ad128d3c356219',
    messagingSenderId: '1020559633116',
    projectId: 'doantotnghiepmydung',
    authDomain: 'doantotnghiepmydung.firebaseapp.com',
    storageBucket: 'doantotnghiepmydung.firebasestorage.app',
    measurementId: 'G-HPN1DDBW3H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuv2gC-lId7SluKnZeLQipKqbcRp-Cnzg',
    appId: '1:1020559633116:android:3bede6ef161365e6356219',
    messagingSenderId: '1020559633116',
    projectId: 'doantotnghiepmydung',
    storageBucket: 'doantotnghiepmydung.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARJ-6yKGpB_TtKEzy_BOWVuu_DMdl8XDo',
    appId: '1:1020559633116:ios:b6617e25312056dc356219',
    messagingSenderId: '1020559633116',
    projectId: 'doantotnghiepmydung',
    storageBucket: 'doantotnghiepmydung.firebasestorage.app',
    iosBundleId: 'com.example.doantotnghiep',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARJ-6yKGpB_TtKEzy_BOWVuu_DMdl8XDo',
    appId: '1:1020559633116:ios:b6617e25312056dc356219',
    messagingSenderId: '1020559633116',
    projectId: 'doantotnghiepmydung',
    storageBucket: 'doantotnghiepmydung.firebasestorage.app',
    iosBundleId: 'com.example.doantotnghiep',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCm2edtdbvMku8A5edTbmGUtsyCC1TX7Js',
    appId: '1:1020559633116:web:c0d0ff06355dfdaa356219',
    messagingSenderId: '1020559633116',
    projectId: 'doantotnghiepmydung',
    authDomain: 'doantotnghiepmydung.firebaseapp.com',
    storageBucket: 'doantotnghiepmydung.firebasestorage.app',
    measurementId: 'G-HMX1TJ1EMT',
  );
}
